# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LoCal1' do

end

target 'LoCal1Tests' do

end

target 'LoCal1UITests' do

end

pod 'Firebase', '>= 2.5.1'

